-- MySQL Script generated by MySQL Workbench
-- Tue May 17 14:25:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`CLIENTS` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` CHAR(40) NOT NULL,
  `adresse1` VARCHAR(255) NOT NULL,
  `adresse2` VARCHAR(255) NOT NULL,
  `adresse3` VARCHAR(255) NOT NULL,
  `code_postale` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `mobile` VARCHAR(10) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`COMMANDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`COMMANDES` (
  `id_commande` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `libelle` VARCHAR(255) NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_commande`),
  INDEX `fk_COMMANDES_CLIENTS_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_COMMANDES_CLIENTS`
    FOREIGN KEY (`id_client`)
    REFERENCES `ecommerce`.`CLIENTS` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`ARTICLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ARTICLES` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(255) NOT NULL,
  `prix_ut` FLOAT NOT NULL,
  `poids` FLOAT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_article`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`CATEGORIES` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  `ARTICLES_id_article` INT NOT NULL,
  PRIMARY KEY (`id_categorie`),
  INDEX `fk_CATEGORIES_ARTICLES1_idx` (`ARTICLES_id_article` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORIES_ARTICLES1`
    FOREIGN KEY (`ARTICLES_id_article`)
    REFERENCES `ecommerce`.`ARTICLES` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`TVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`TVA` (
  `id_tva` INT NOT NULL AUTO_INCREMENT,
  `taux` FLOAT NOT NULL,
  `libelle_taux` VARCHAR(45) NOT NULL,
  `ARTICLES_id_article` INT NOT NULL,
  PRIMARY KEY (`id_tva`),
  INDEX `fk_TVA_ARTICLES1_idx` (`ARTICLES_id_article` ASC) VISIBLE,
  CONSTRAINT `fk_TVA_ARTICLES1`
    FOREIGN KEY (`ARTICLES_id_article`)
    REFERENCES `ecommerce`.`ARTICLES` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`ARTICLES_has_COMMANDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ARTICLES_has_COMMANDES` (
  `id_article` INT NOT NULL,
  `id_commande` INT NOT NULL,
  `quantite` INT NULL,
  PRIMARY KEY (`id_article`, `id_commande`),
  INDEX `fk_ARTICLES_has_COMMANDES_COMMANDES1_idx` (`id_commande` ASC) VISIBLE,
  INDEX `fk_ARTICLES_has_COMMANDES_ARTICLES1_idx` (`id_article` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICLES_has_COMMANDES_ARTICLES1`
    FOREIGN KEY (`id_article`)
    REFERENCES `ecommerce`.`ARTICLES` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLES_has_COMMANDES_COMMANDES1`
    FOREIGN KEY (`id_commande`)
    REFERENCES `ecommerce`.`COMMANDES` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
